const DIGIMON_DATA = [
  {
    id: 1,
    title: "Agumon",
    routeName: "agumon",
    items: [
      {
        id: 1,
        name: "Koromon",
        imageUrl: "https://i.ibb.co/ggy60GQ/koromon.jpg",
        children: "Taichi Yagami",
        imageUrlChildren: "https://i.ibb.co/7tq1y3y/tai.jpg",
      },
      {
        id: 2,
        name: "Agumon",
        imageUrl: "https://i.ibb.co/dgQbn4P/agumon.jpg",
        children: "Taichi Yagami",
        imageUrlChildren: "https://i.ibb.co/7tq1y3y/tai.jpg",
      },
      {
        id: 3,
        name: "Greymon",
        imageUrl: "https://i.ibb.co/yNf0D23/greymon.jpg",
        children: "Taichi Yagami",
        imageUrlChildren: "https://i.ibb.co/7tq1y3y/tai.jpg",
      },
      {
        id: 4,
        name: "MetalGreymon",
        imageUrl: "https://i.ibb.co/XYrZtzV/metalgreymon.jpg",
        children: "Taichi Yagami",
        imageUrlChildren: "https://i.ibb.co/7tq1y3y/tai.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "Gabumon",
    routeName: "gabumon",
    items: [
      {
        id: 10,
        name: "Tsunomon",
        imageUrl: "https://i.ibb.co/XVj4ynj/tsunomon.jpg",
        children: "Yamato Ishida",
        imageUrlChildren: "https://i.ibb.co/bvhyDnV/matt.jpg",
      },
      {
        id: 11,
        name: "Gabumon",
        imageUrl: "https://i.ibb.co/n6qmpwr/gabumon.jpg",
        children: "Yamato Ishida",
        imageUrlChildren: "https://i.ibb.co/bvhyDnV/matt.jpg",
      },
      {
        id: 12,
        name: "Garurumon",
        imageUrl: "https://i.ibb.co/vP754wb/garurumon.jpg",
        children: "Yamato Ishida",
        imageUrlChildren: "https://i.ibb.co/bvhyDnV/matt.jpg",
      },
      {
        id: 13,
        name: "WereGarurumon",
        imageUrl: "https://i.ibb.co/K93N24x/were-Garurumon.jpg",
        children: "Yamato Ishida",
        imageUrlChildren: "https://i.ibb.co/bvhyDnV/matt.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Patamon",
    routeName: "patamon",
    items: [
      {
        id: 18,
        name: "Tokomon",
        imageUrl: "https://i.ibb.co/mNWqKkF/tokomon.jpg",
        children: "Takeru Takaishi",
        imageUrlChildren: "https://i.ibb.co/BrSdf3X/tk.jpg",
      },
      {
        id: 19,
        name: "Patamon",
        imageUrl: "https://i.ibb.co/d4R9YTM/patamon.jpg",
        children: "Takeru Takaishi",
        imageUrlChildren: "https://i.ibb.co/BrSdf3X/tk.jpg",
      },
      {
        id: 20,
        name: "Angemon",
        imageUrl: "https://i.ibb.co/1LfrKHY/angemon.jpg",
        children: "Takeru Takaishi",
        imageUrlChildren: "https://i.ibb.co/BrSdf3X/tk.jpg",
      },
      {
        id: 21,
        name: "Pegasusmon",
        imageUrl: "https://i.ibb.co/PYdCXm0/pegasusmon.jpg",
        children: "Takeru Takaishi",
        imageUrlChildren: "https://i.ibb.co/BrSdf3X/tk.jpg",
      },
    ],
  },
  {
    id: 4,
    title: "Tentomon",
    routeName: "tentomon",
    items: [
      {
        id: 22,
        name: "Mochimon",
        imageUrl: "https://i.ibb.co/jZXg2rX/mochimon.jpg",
        children: "Koshiro Izumi",
        imageUrlChildren: "https://i.ibb.co/TBGyyjF/izzy.jpg",
      },
      {
        id: 23,
        name: "Tentomon",
        imageUrl: "https://i.ibb.co/z8hwm0Z/tentomon.jpg",
        children: "Koshiro Izumi",
        imageUrlChildren: "https://i.ibb.co/TBGyyjF/izzy.jpg",
      },
      {
        id: 24,
        name: "Kabuterimon",
        imageUrl: "https://i.ibb.co/7NjNH2s/kabuterimon.jpg",
        children: "Koshiro Izumi",
        imageUrlChildren: "https://i.ibb.co/TBGyyjF/izzy.jpg",
      },
      {
        id: 25,
        name: "MegaKabuterimon",
        imageUrl: "https://i.ibb.co/Bt8SvtK/mega-Kabuterimon.jpg",
        children: "Koshiro Izumi",
        imageUrlChildren: "https://i.ibb.co/TBGyyjF/izzy.jpg",
      },
    ],
  },
  {
    id: 5,
    title: "Gomamon",
    routeName: "gomamon",
    items: [
      {
        id: 26,
        name: "Pukamon",
        imageUrl: "https://i.ibb.co/nfXT93q/pukamon.jpg",
        children: "Joe Kido",
        imageUrlChildren: "https://i.ibb.co/d0DLtbZ/joe.jpg",
      },
      {
        id: 27,
        name: "Gomamon",
        imageUrl: "https://i.ibb.co/YQBq4rD/gomamon.jpg",
        children: "Joe Kido",
        imageUrlChildren: "https://i.ibb.co/d0DLtbZ/joe.jpg",
      },
      {
        id: 28,
        name: "Ikkakumon",
        imageUrl: "https://i.ibb.co/NSJdxZC/ikkakumon.jpg",
        children: "Joe Kido",
        imageUrlChildren: "https://i.ibb.co/d0DLtbZ/joe.jpg",
      },
      {
        id: 29,
        name: "Zudomon",
        imageUrl: "https://i.ibb.co/py8KVz3/zudomon.jpg",
        children: "Joe Kido",
        imageUrlChildren: "https://i.ibb.co/d0DLtbZ/joe.jpg",
      },
    ],
  },
  {
    id: 6,
    title: "Palmon",
    routeName: "palmon",
    items: [
      {
        id: 30,
        name: "Tanemon",
        imageUrl: "https://i.ibb.co/sv7dNq8/tanemon.jpg",
        children: "Mimi Tachikawa",
        imageUrlChildren: "https://i.ibb.co/yN68YTH/mimi.jpg",
      },
      {
        id: 31,
        name: "Palmon",
        imageUrl: "https://i.ibb.co/yfzfbx5/palmon.jpg",
        children: "Mimi Tachikawa",
        imageUrlChildren: "https://i.ibb.co/yN68YTH/mimi.jpg",
      },
      {
        id: 32,
        name: "Togemon",
        imageUrl: "https://i.ibb.co/wB8k1Ms/togemon.jpg",
        children: "Mimi Tachikawa",
        imageUrlChildren: "https://i.ibb.co/yN68YTH/mimi.jpg",
      },
      {
        id: 33,
        name: "Lillymon",
        imageUrl: "https://i.ibb.co/3ryb9s8/lillymon.jpg",
        children: "Mimi Tachikawa",
        imageUrlChildren: "https://i.ibb.co/yN68YTH/mimi.jpg",
      },
    ],
  },
];

export default DIGIMON_DATA;